CREATE DATABASE CurrencyConverter
GO
USE CurrencyConverter
GO

CREATE TABLE Currency(
	id						INT				NOT NULL	IDENTITY,
	country					VARCHAR(100)	NOT NULL,
	[name]					VARCHAR(100)	NOT NULL,
	abbreviation			VARCHAR(5)		NOT NULL,
	PRIMARY KEY (id),
);

CREATE TABLE [Period](
	id						INT				NOT NULL	IDENTITY,
	[name]					VARCHAR(100)	NOT NULL,
	PRIMARY KEY (id),
);

CREATE TABLE USDExchangeRate(
	id						INT				NOT NULL	IDENTITY,
	period_id				INT				NOT NULL,
	currency_id				INT				NOT NULL,
	rate					DECIMAL(13,4)	NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (period_id) REFERENCES [Period](id),
	FOREIGN KEY (currency_id) REFERENCES Currency(id),
);

INSERT INTO [Currency](country, [name], abbreviation) VALUES('Argentina', 'Argentine Peso', 'ARS')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Australia', 'Australian Dollar', 'AUD')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Brazil', 'Brazilian Real', 'BRL')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Canada', 'Canadian Dollar', 'CAD')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Chile', 'Chilean Peso', 'CLP')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('China', 'Renminbi', 'CNY')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Colombia', 'Colombian Peso', 'COP')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Costa Rica', 'Costa Rican Colón', 'CRC')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Czech Republic', 'Czech Koruna', 'CZK')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Denmark', 'Danish Krone', 'DKK')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Hungary', 'Hungarian Forint', 'HUF')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Iceland', 'Icelandic Króna', 'ISK')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('India', 'Indian Rupee', 'INR')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Indonesia', 'Indonesian Rupiah', 'IDR')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Israel', 'Israeli New Shekel', 'ILS')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Japan', 'Japanese Yen', 'JPY')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Mexico', 'Mexican Peso', 'MXN')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('New Zealand', 'New Zealand Dollar', 'NZD')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Norway', 'Norwegian Krone', 'NOK')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Poland', 'Polish Złoty', 'PLN')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Russia', 'Russian Ruble', 'RUB')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('South Africa', 'South African Rand', 'ZAR')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('South Korea', 'South Korea Won', 'KRW')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Sweden', 'Swedish Krona', 'SEK')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Switzerland', 'Swiss Franc', 'CHF')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('Turkey', 'Turkish Lira', 'TRY')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('United Kingdom', 'Pound Sterling', 'GBP')
INSERT INTO [Currency](country, [name], abbreviation) VALUES('United States', 'United States Dollar', 'USD')


INSERT INTO [Period](name) VALUES('January 2023')
INSERT INTO [Period](name) VALUES('February 2023')
INSERT INTO [Period](name) VALUES('March 2023')
INSERT INTO [Period](name) VALUES('April 2023')
INSERT INTO [Period](name) VALUES('May 2023')
INSERT INTO [Period](name) VALUES('June 2023')
INSERT INTO [Period](name) VALUES('July 2023')
INSERT INTO [Period](name) VALUES('August 2023')
INSERT INTO [Period](name) VALUES('September 2023')
INSERT INTO [Period](name) VALUES('October 2023')
INSERT INTO [Period](name) VALUES('November 2023')
INSERT INTO [Period](name) VALUES('December 2023')


INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 1, 296.258)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 2, 1.505)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 3, 4.994)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 4, 1.349)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 5, 840.159)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 6, 7.084)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 7, 4326.692)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 8, 541.609)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 9, 22.197)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 10, 6.889)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 11, 353.151)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 12, 137.952)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 13, 82.601)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 14, 15236.88)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 15, 3.686)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 16, 140.506)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 17, 17.693)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 18, 1.629)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 19, 10.559)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 20, 4.202)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 21, 85.162)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 22, 18.45)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 23, 1306.011)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 24, 10.603)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 25, 0.898)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 26, 23.785)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(1, 27, 0.805)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 1, 191.79)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 2, 1.447)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 3, 5.171)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 4, 1.345)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 5, 801.342)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 6, 6.836)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 7, 4822.552)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 8, 565.093)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 9, 22.129)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 10, 6.949)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 11, 359.193)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 12, 142.85)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 13, 82.609)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 14, 15126)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 15, 3.543)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 16, 132.784)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 17, 18.554)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 18, 1.59)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 19, 10.223)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 20, 4.427)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 21, 73.005)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 22, 17.886)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 23, 1275.16)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 24, 10.432)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 25, 0.924)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 26, 18.844)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(2, 27, 0.827)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 1, 202.951)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 2, 1.495)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 3, 5.211)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 4, 1.368)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 5, 807.399)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 6, 6.897)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 7, 4759.074)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 8, 545.715)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 9, 22.123)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 10, 6.955)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 11, 359.914)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 12, 140.13)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 13, 82.289)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 14, 15300.71)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 15, 3.617)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 16, 133.722)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 17, 18.33)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 18, 1.611)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 19, 10.543)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 20, 4.384)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 21, 76.083)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 22, 18.269)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 23, 1305.278)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 24, 10.474)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 25, 0.926)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 26, 18.999)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(3, 27, 0.824)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 1, 216.366)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 2, 1.494)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 3, 5.019)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 4, 1.348)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 5, 804.977)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 6, 6.889)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 7, 4530.264)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 8, 535.88)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 9, 21.378)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 10, 6.795)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 11, 343.039)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 12, 136.45)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 13, 82.021)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 14, 14866.71)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 15, 3.623)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 16, 133.39)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 17, 18.058)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 18, 1.61)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 19, 10.493)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 20, 4.233)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 21, 80.88)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 22, 18.176)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 23, 1322.19)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 24, 10.343)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 25, 0.898)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 26, 19.337)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(4, 27, 0.803)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 1, 231.008)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 2, 1.504)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 3, 4.982)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 4, 1.352)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 5, 799.351)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 6, 6.994)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 7, 4536.51)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 8, 537.864)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 9, 21.703)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 10, 6.848)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 11, 342.767)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 12, 138.348)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 13, 82.343)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 14, 14810.86)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 15, 3.666)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 16, 137.406)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 17, 17.703)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 18, 1.61)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 19, 10.775)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 20, 4.177)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 21, 78.937)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 22, 19.053)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 23, 1327.691)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 24, 10.437)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 25, 0.897)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 26, 19.748)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(5, 27, 0.802)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 1, 248.575)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 2, 1.491)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 3, 4.851)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 4, 1.329)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 5, 799.51)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 6, 7.162)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 7, 4205.262)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 8, 540.439)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 9, 21.86)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 10, 6.87)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 11, 342.149)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 12, 137.773)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 13, 82.234)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 14, 14932)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 15, 3.645)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 16, 141.316)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 17, 17.201)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 18, 1.63)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 19, 10.81)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 20, 4.12)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 21, 83.147)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 22, 18.756)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 23, 1297.141)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 24, 10.764)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 25, 0.901)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 26, 23.697)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(6, 27, 0.792)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 1, 266.226)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 2, 1.484)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 3, 4.8)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 4, 1.322)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 5, 815.017)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 6, 7.185)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 7, 4054.683)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 8, 541.028)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 9, 21.599)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 10, 6.739)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 11, 342.851)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 12, 132.857)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 13, 82.152)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 14, 15039.75)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 15, 3.67)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 16, 141.051)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 17, 16.862)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 18, 1.605)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 19, 10.264)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 20, 4.019)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 21, 90.417)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 22, 18.184)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 23, 1284.133)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 24, 10.524)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 25, 0.874)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 26, 26.499)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(7, 27, 0.776)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 1, 321.755)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 2, 1.541)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 3, 4.903)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 4, 1.348)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 5, 856.544)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 6, 7.253)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 7, 4077.895)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 8, 538.248)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 9, 22.104)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 10, 6.832)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 11, 353.349)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 12, 131.826)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 13, 82.785)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 14, 15245.14)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 15, 3.746)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 16, 144.676)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 17, 16.938)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 18, 1.668)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 19, 10.463)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 20, 4.086)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 21, 95.263)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 22, 18.754)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 23, 1321.139)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 24, 10.819)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 25, 0.878)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 26, 26.943)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(8, 27, 0.787)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 1, 349.505)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 2, 1.557)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 3, 4.936)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 4, 1.354)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 5, 886.605)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 6, 7.299)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 7, 4007.122)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 8, 535.044)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 9, 22.832)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 10, 6.98)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 11, 361.742)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 12, 135.191)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 13, 83.047)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 14, 15354.2)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 15, 3.82)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 16, 147.646)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 17, 17.26)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 18, 1.687)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 19, 10.72)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 20, 4.303)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 21, 96.649)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 22, 18.978)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 23, 1332.933)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 24, 11.086)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 25, 0.898)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 26, 26.999)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(9, 27, 0.807)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 1, 349.52)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 2, 1.574)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 3, 5.064)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 4, 1.371)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 5, 925.096)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 6, 7.312)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 7, 4227.934)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 8, 532.356)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 9, 23.276)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 10, 7.063)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 11, 364.773)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 12, 138.773)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 13, 83.235)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 14, 15741.23)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 15, 3.978)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 16, 149.545)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 17, 17.998)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 18, 1.697)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 19, 11.009)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 20, 4.271)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 21, 97.007)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 22, 19.051)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 23, 1350.564)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 24, 11.024)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 25, 0.904)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 26, 27.86)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(10, 27, 0.822)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 1, 353.318)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 2, 1.541)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 3, 4.898)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 4, 1.371)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 5, 885.239)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 6, 7.236)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 7, 4035.887)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 8, 530.928)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 9, 22.665)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 10, 6.9)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 11, 350.841)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 12, 140.091)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 13, 83.298)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 14, 15617.41)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 15, 3.806)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 16, 149.851)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 17, 17.34)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 18, 1.667)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 19, 10.916)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 20, 4.074)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 21, 90.572)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 22, 18.538)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 23, 1307.7)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 24, 10.696)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 25, 0.892)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 26, 28.638)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(11, 27, 0.805)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 1, 641.94)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 2, 1.495)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 3, 4.897)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 4, 1.341)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 5, 875.756)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 6, 7.15)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 7, 3948.097)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 8, 524.224)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 9, 22.443)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 10, 6.832)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 11, 349.872)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 12, 137.952)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 13, 83.299)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 14, 15513.37)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 15, 3.666)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 16, 144.072)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 17, 17.136)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 18, 1.607)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 19, 10.547)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 20, 3.97)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 21, 90.76)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 22, 18.67)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 23, 1303.776)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 24, 10.259)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 25, 0.865)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 26, 29.078)
INSERT INTO USDExchangeRate(period_id, currency_id, rate) VALUES(12, 27, 0.79)



--USE master
--GO
--DROP DATABASE CurrencyConverter